### ISSUE TITLE
The webroot of Open Zaakbrug shows an 404 errorpage

### ISSUE THREAD

**Issue by EduardWitteveen** [Sudwest-Fryslan/OpenZaakBrug#102]
When a user visits Open Zaakbrug with a browser, an errorpage is shown. 
This can give the impression that Open Zaakbrug is not running as expected.
It would be nice to have a friendly page giving the user a warm welcome

**Comment by EduardWitteveen** [comment]
```
Whitelabel Error PageThis application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Feb 02 12:00:31 CET 2021
There was an unexpected error (type=Not Found, status=404).
Could not load a convertor for
		 path: '/' with soapaction: '' available services:
		 path: 'translate/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerZaakIdentificatie_Di02'
		 path: 'translate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/creeerZaak_Lk01'
		 path: 'translate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/updateZaak_Lk01'
		 path: 'translate/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerDocumentIdentificatie_Di02'
		 path: 'translate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/voegZaakdocumentToe_Lk01'
		 path: 'translate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefLijstZaakdocumenten_Lv01'
		 path: 'translate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdocumentLezen_Lv01'
		 path: 'translate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/actualiseerZaakstatus_Lk01'
		 path: 'translate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdetails_Lv01'
		 path: 'translate/generic/stufzkn/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/zakLv01'
		 path: 'proxy/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerZaakIdentificatie_Di02'
		 path: 'proxy/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/creeerZaak_Lk01'
		 path: 'proxy/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/updateZaak_Lk01'
		 path: 'proxy/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerDocumentIdentificatie_Di02'
		 path: 'proxy/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/voegZaakdocumentToe_Lk01'
		 path: 'proxy/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefLijstZaakdocumenten_Lv01'
		 path: 'proxy/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdocumentLezen_Lv01'
		 path: 'proxy/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/actualiseerZaakstatus_Lk01'
		 path: 'proxy/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdetails_Lv01'
		 path: 'proxy/generic/stufzkn/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/zakLv01'
		 path: 'replicate/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerZaakIdentificatie_Di02'
		 path: 'replicate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/creeerZaak_Lk01'
		 path: 'replicate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/updateZaak_Lk01'
		 path: 'replicate/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerDocumentIdentificatie_Di02'
		 path: 'replicate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/voegZaakdocumentToe_Lk01'
		 path: 'replicate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefLijstZaakdocumenten_Lv01'
		 path: 'replicate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdocumentLezen_Lv01'
		 path: 'replicate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/actualiseerZaakstatus_Lk01'
		 path: 'replicate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdetails_Lv01'
		 path: 'replicate/generic/stufzkn/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/zakLv01'
org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND "Could not load a convertor for
		 path: '/' with soapaction: '' available services:
		 path: 'translate/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerZaakIdentificatie_Di02'
		 path: 'translate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/creeerZaak_Lk01'
		 path: 'translate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/updateZaak_Lk01'
		 path: 'translate/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerDocumentIdentificatie_Di02'
		 path: 'translate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/voegZaakdocumentToe_Lk01'
		 path: 'translate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefLijstZaakdocumenten_Lv01'
		 path: 'translate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdocumentLezen_Lv01'
		 path: 'translate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/actualiseerZaakstatus_Lk01'
		 path: 'translate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdetails_Lv01'
		 path: 'translate/generic/stufzkn/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/zakLv01'
		 path: 'proxy/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerZaakIdentificatie_Di02'
		 path: 'proxy/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/creeerZaak_Lk01'
		 path: 'proxy/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/updateZaak_Lk01'
		 path: 'proxy/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerDocumentIdentificatie_Di02'
		 path: 'proxy/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/voegZaakdocumentToe_Lk01'
		 path: 'proxy/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefLijstZaakdocumenten_Lv01'
		 path: 'proxy/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdocumentLezen_Lv01'
		 path: 'proxy/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/actualiseerZaakstatus_Lk01'
		 path: 'proxy/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdetails_Lv01'
		 path: 'proxy/generic/stufzkn/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/zakLv01'
		 path: 'replicate/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerZaakIdentificatie_Di02'
		 path: 'replicate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/creeerZaak_Lk01'
		 path: 'replicate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/updateZaak_Lk01'
		 path: 'replicate/generic/zds/VrijBericht' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/genereerDocumentIdentificatie_Di02'
		 path: 'replicate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/voegZaakdocumentToe_Lk01'
		 path: 'replicate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefLijstZaakdocumenten_Lv01'
		 path: 'replicate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdocumentLezen_Lv01'
		 path: 'replicate/generic/zds/OntvangAsynchroon' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/actualiseerZaakstatus_Lk01'
		 path: 'replicate/generic/zds/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdetails_Lv01'
		 path: 'replicate/generic/stufzkn/BeantwoordVraag' soapaction: 'http://www.egem.nl/StUF/sector/zkn/0310/zakLv01'
	 " at nl.haarlem.translations.zdstozgw.converter.ConverterFactory.getConverter(ConverterFactory.java:46) at nl.haarlem.translations.zdstozgw.controller.SoapController.HandleRequest(SoapController.java:53) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:834)

```
