### ISSUE TITLE
Replicate zaak should keep working when zaakdocument is missing

### ISSUE THREAD

**Issue by EduardWitteveen** [Sudwest-Fryslan/OpenZaakBrug#141]
Replicate zaak should keep working when zaakdocument is missing.
When the zaaksystem says that the documentidentification (getlijst) is there, but the getdocument fails, the system should continue with an warning.

**Comment by EduardWitteveen** [comment]
Error message:
```
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header/>
<SOAP-ENV:Body>
<SOAP-ENV:Fault>
<faultcode xmlns:env="http://www.w3.org/2003/05/soap-envelope">env:Receiver</faultcode>
<faultstring>java.lang.NullPointerException</faultstring>
<detail>
<Fo03Bericht xmlns="http://www.egem.nl/StUF/StUF0301" xmlns:ns2="http://www.egem.nl/StUF/sector/zkn/0310">
<stuurgegevens>
<berichtcode>Fo03</berichtcode>
<zender>
<organisatie>1900</organisatie>
<applicatie>CDR</applicatie>
</zender>
<ontvanger>
<organisatie>1900</organisatie>
<applicatie>RepliceerZaken</applicatie>
</ontvanger>
<referentienummer>ozb-a85af9bc-df84-44ae-b641-1d3464310ffa</referentienummer>
<tijdstipBericht>20210419102931</tijdstipBericht>
<crossRefnummer>20210419102929</crossRefnummer>
</stuurgegevens>
<body>
<code>StUF058</code>
<plek>server</plek>
<omschrijving>java.lang.NullPointerException</omschrijving>
<details>java.lang.NullPointerException
at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.copyDocument(Replicator.java:169)
at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.checkVoegZaakDocumentToe(Replicator.java:139)
at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.replicateZaak(Replicator.java:53)
at nl.haarlem.translations.zdstozgw.converter.impl.replicate.GeefZaakDetailsReplicator.execute(GeefZaakDetailsReplicator.java:36)
at nl.haarlem.translations.zdstozgw.requesthandler.impl.LoggingRequestHandler.execute(LoggingRequestHandler.java:54)
at nl.haarlem.translations.zdstozgw.controller.SoapController.HandleRequest(SoapController.java:116)
at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.web.method.supp</details>
<detailsXML>
<todo>&lt;ns0:Envelope xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://www.egem.nl/StUF/sector/zkn/0310" xmlns:ns2="http://www.egem.nl/StUF/StUF0301"&gt;
&lt;ns0:Header /&gt;
&lt;ns0:Body&gt;
&lt;ns1:zakLv01&gt;
&lt;ns1:stuurgegevens&gt;
&lt;ns2:berichtcode&gt;Lv01&lt;/ns2:berichtcode&gt;
&lt;ns2:zender&gt;
&lt;ns2:organisatie&gt;1900&lt;/ns2:organisatie&gt;
&lt;ns2:applicatie&gt;RepliceerZaken&lt;/ns2:applicatie&gt;
&lt;/ns2:zender&gt;
&lt;ns2:ontvanger&gt;
&lt;ns2:organisatie&gt;1900&lt;/ns2:organisatie&gt;
&lt;ns2:applicatie&gt;CDR&lt;/ns2:applicatie&gt;
&lt;/ns2:ontvanger&gt;
&lt;ns2:referentienummer&gt;20210419102929&lt;/ns2:referentienummer&gt;
&lt;ns2:tijdstipBericht&gt;20210419102929&lt;/ns2:tijdstipBericht&gt;
&lt;ns2:entiteittype&gt;ZAK&lt;/ns2:entiteittype&gt;
&lt;/ns1:stuurgegevens&gt;
&lt;ns1:parameters&gt;
&lt;ns2:sortering&gt;0&lt;/ns2:sortering&gt;
&lt;ns2:indicatorVervolgvraag&gt;false&lt;/ns2:indicatorVervolgvraag&gt;
&lt;ns2:maximumAantal&gt;1&lt;/ns2:maximumAantal&gt;
&lt;/ns1:parameters&gt;
&lt;ns1:gelijk ns2:entiteittype="ZAK"&gt;
&lt;ns1:identificatie&gt;1900332695&lt;/ns1:identificatie&gt;
&lt;/ns1:gelijk&gt;
&lt;ns1:scope&gt;
&lt;ns1:object ns2:entiteittype="ZAK" ns2:scope="alles" /&gt;
&lt;/ns1:scope&gt;
&lt;/ns1:zakLv01&gt;
&lt;/ns0:Body&gt;
&lt;/ns0:Envelope&gt;</todo>
</detailsXML>
</body>
</Fo03Bericht>
</detail>
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

```

**Comment by EduardWitteveen** [comment]
Still not solved:

Request: 
```
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header/>
<SOAP-ENV:Body>
<ns2:edcLv01 xmlns:ns1="http://www.egem.nl/StUF/StUF0301" xmlns:ns2="http://www.egem.nl/StUF/sector/zkn/0310">
<ns2:stuurgegevens>
<ns1:berichtcode>Lv01</ns1:berichtcode>
<ns1:zender>
<ns1:organisatie>1900</ns1:organisatie>
<ns1:applicatie>RepliceerZaken</ns1:applicatie>
</ns1:zender>
<ns1:ontvanger>
<ns1:organisatie>1900</ns1:organisatie>
<ns1:applicatie>CDR</ns1:applicatie>
</ns1:ontvanger>
<ns1:referentienummer>20210420115644</ns1:referentienummer>
<ns1:tijdstipBericht>20210420115644</ns1:tijdstipBericht>
<ns1:entiteittype>EDC</ns1:entiteittype>
</ns2:stuurgegevens>
<ns2:parameters>
<ns1:sortering>0</ns1:sortering>
<ns1:indicatorVervolgvraag>false</ns1:indicatorVervolgvraag>
</ns2:parameters>
<ns2:gelijk ns1:entiteittype="EDC">
<ns2:identificatie>1900545032</ns2:identificatie>
</ns2:gelijk>
<ns2:scope>
<ns2:object ns1:entiteittype="EDC" ns1:scope="alles"/>
</ns2:scope>
</ns2:edcLv01>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

```
Response:

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Body>
		<edcLa01 xmlns="http://www.egem.nl/StUF/sector/zkn/0310"
       			xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
       			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<stuurgegevens>
				<StUF:berichtcode>La01</StUF:berichtcode>
				<StUF:zender>
					<StUF:organisatie>1900</StUF:organisatie>
					<StUF:applicatie>CDR</StUF:applicatie>
				</StUF:zender>
				<StUF:ontvanger>
					<StUF:organisatie>1900</StUF:organisatie>
					<StUF:applicatie>RepliceerZaken</StUF:applicatie>
				</StUF:ontvanger>
				<StUF:referentienummer>5894e856-a32b-4841-b85c-45351a541186</StUF:referentienummer>
				<StUF:tijdstipBericht>20210420115647034</StUF:tijdstipBericht>
				<StUF:crossRefnummer>20210420115644</StUF:crossRefnummer>
				<StUF:entiteittype>EDC</StUF:entiteittype>
			</stuurgegevens>
			<parameters>
				<StUF:indicatorVervolgvraag>false</StUF:indicatorVervolgvraag>
			</parameters>
		</edcLa01>
	</s:Body>
</s:Envelope>
```

Error:
```
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header/>
<SOAP-ENV:Body>
<SOAP-ENV:Fault>
<faultcode xmlns:env="http://www.w3.org/2003/05/soap-envelope">env:Receiver</faultcode>
<faultstring>java.lang.NullPointerException</faultstring>
<detail>
<Fo03Bericht xmlns="http://www.egem.nl/StUF/StUF0301" xmlns:ns2="http://www.egem.nl/StUF/sector/zkn/0310">
<stuurgegevens>
<berichtcode>Fo03</berichtcode>
<zender>
<organisatie>1900</organisatie>
<applicatie>CDR</applicatie>
</zender>
<ontvanger>
<organisatie>1900</organisatie>
<applicatie>RepliceerZaken</applicatie>
</ontvanger>
<referentienummer>ozb-3122c300-1177-4ab1-8ad9-3873a0a6a5cb</referentienummer>
<tijdstipBericht>20210420115645</tijdstipBericht>
<crossRefnummer>20210420115644</crossRefnummer>
</stuurgegevens>
<body>
<code>StUF058</code>
<plek>server</plek>
<omschrijving>java.lang.NullPointerException</omschrijving>
<details>java.lang.NullPointerException
at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.copyDocument(Replicator.java:174)
at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.checkVoegZaakDocumentToe(Replicator.java:140)
at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.replicateZaak(Replicator.java:54)
at nl.haarlem.translations.zdstozgw.converter.impl.replicate.GeefZaakDetailsReplicator.execute(GeefZaakDetailsReplicator.java:42)
at nl.haarlem.translations.zdstozgw.requesthandler.impl.LoggingRequestHandler.execute(LoggingRequestHandler.java:54)
at nl.haarlem.translations.zdstozgw.controller.SoapController.HandleRequest(SoapController.java:116)
at jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.web.method.supp</details>
<detailsXML>
<todo>&lt;ns0:Envelope xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://www.egem.nl/StUF/sector/zkn/0310" xmlns:ns2="http://www.egem.nl/StUF/StUF0301"&gt;
&lt;ns0:Header /&gt;
&lt;ns0:Body&gt;
&lt;ns1:zakLv01&gt;
&lt;ns1:stuurgegevens&gt;
&lt;ns2:berichtcode&gt;Lv01&lt;/ns2:berichtcode&gt;
&lt;ns2:zender&gt;
&lt;ns2:organisatie&gt;1900&lt;/ns2:organisatie&gt;
&lt;ns2:applicatie&gt;RepliceerZaken&lt;/ns2:applicatie&gt;
&lt;/ns2:zender&gt;
&lt;ns2:ontvanger&gt;
&lt;ns2:organisatie&gt;1900&lt;/ns2:organisatie&gt;
&lt;ns2:applicatie&gt;CDR&lt;/ns2:applicatie&gt;
&lt;/ns2:ontvanger&gt;
&lt;ns2:referentienummer&gt;20210420115644&lt;/ns2:referentienummer&gt;
&lt;ns2:tijdstipBericht&gt;20210420115644&lt;/ns2:tijdstipBericht&gt;
&lt;ns2:entiteittype&gt;ZAK&lt;/ns2:entiteittype&gt;
&lt;/ns1:stuurgegevens&gt;
&lt;ns1:parameters&gt;
&lt;ns2:sortering&gt;0&lt;/ns2:sortering&gt;
&lt;ns2:indicatorVervolgvraag&gt;false&lt;/ns2:indicatorVervolgvraag&gt;
&lt;ns2:maximumAantal&gt;1&lt;/ns2:maximumAantal&gt;
&lt;/ns1:parameters&gt;
&lt;ns1:gelijk ns2:entiteittype="ZAK"&gt;
&lt;ns1:identificatie&gt;1900332695&lt;/ns1:identificatie&gt;
&lt;/ns1:gelijk&gt;
&lt;ns1:scope&gt;
&lt;ns1:object ns2:entiteittype="ZAK" ns2:scope="alles" /&gt;
&lt;/ns1:scope&gt;
&lt;/ns1:zakLv01&gt;
&lt;/ns0:Body&gt;
&lt;/ns0:Envelope&gt;</todo>
</detailsXML>
</body>
</Fo03Bericht>
</detail>
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

```
