### ISSUE TITLE
Make Verint Kana work

### ISSUE THREAD

**Issue by EduardWitteveen** [Sudwest-Fryslan/OpenZaakBrug#180]
The KCC applicatie retrieves the zaak-information regaring a person by issuing the following request on the endpoint:  http://localhost:8080/translate/generic/stufzkn/BeantwoordVraag

Request:
```
<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Header/>
	<soapenv:Body>
		<ZKN:zakLv01 xmlns:ZKN="http://www.egem.nl/StUF/sector/zkn/0310"
           			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           			xmlns:BG="http://www.egem.nl/StUF/sector/bg/0310"
           			xmlns:StUF="http://www.egem.nl/StUF/StUF0301">
			<ZKN:stuurgegevens>
				<StUF:berichtcode>Lv01</StUF:berichtcode>
				<StUF:entiteittype>ZAK</StUF:entiteittype>
			</ZKN:stuurgegevens>
			<ZKN:parameters>
				<StUF:sortering>0</StUF:sortering>
				<StUF:indicatorVervolgvraag>false</StUF:indicatorVervolgvraag>
			</ZKN:parameters>
			<ZKN:gelijk StUF:entiteittype="ZAK">
				<ZKN:heeftAlsInitiator StUF:entiteittype="ZAKBTRINI">
					<ZKN:gerelateerde>
						<ZKN:identificatie>11111111110</ZKN:identificatie>
					</ZKN:gerelateerde>
				</ZKN:heeftAlsInitiator>
			</ZKN:gelijk>
			<ZKN:scope>
				<ZKN:object StUF:entiteittype="ZAK">
					<ZKN:identificatie xsi:nil="true" />
					<ZKN:omschrijving xsi:nil="true" />
					<ZKN:toelichting xsi:nil="true" />
					<ZKN:resultaat>
						<ZKN:omschrijving xsi:nil="true" />
						<ZKN:toelichting xsi:nil="true" />
					</ZKN:resultaat>
					<ZKN:startdatum xsi:nil="true" />
					<ZKN:registratiedatum xsi:nil="true" />
					<ZKN:publicatiedatum xsi:nil="true" />
					<ZKN:einddatumGepland xsi:nil="true" />
					<ZKN:uiterlijkeEinddatum xsi:nil="true" />
					<ZKN:einddatum xsi:nil="true" />
					<ZKN:opschorting>
						<ZKN:indicatie xsi:nil="true" />
						<ZKN:reden xsi:nil="true" />
					</ZKN:opschorting>
					<ZKN:verlenging>
						<ZKN:duur xsi:nil="true" />
						<ZKN:reden xsi:nil="true" />
					</ZKN:verlenging>
					<ZKN:betalingsIndicatie xsi:nil="true" />
					<ZKN:laatsteBetaaldatum xsi:nil="true" />
					<ZKN:archiefnominatie xsi:nil="true" />
					<ZKN:datumVernietigingDossier xsi:nil="true" />
					<ZKN:zaakniveau xsi:nil="true" />
					<ZKN:deelzakenIndicatie xsi:nil="true" />
					<ZKN:isVan StUF:entiteittype="ZAKZKT">
						<ZKN:gerelateerde StUF:entiteittype="ZKT">
							<ZKN:omschrijving xsi:nil="true" />
							<ZKN:code xsi:nil="true" />
						</ZKN:gerelateerde>
					</ZKN:isVan>
					<ZKN:heeftBetrekkingOp StUF:entiteittype="ZAKOBJ">
						<ZKN:gerelateerde/>
						<ZKN:omschrijving/>
					</ZKN:heeftBetrekkingOp>
					<ZKN:heeftAlsBelanghebbende StUF:entiteittype="ZAKBTRBLH">
						<ZKN:gerelateerde/>
						<ZKN:omschrijving/>
						<ZKN:code/>
						<ZKN:toelichting/>
					</ZKN:heeftAlsBelanghebbende>
					<ZKN:heeftAlsGemachtigde StUF:entiteittype="ZAKBTRGMC">
						<ZKN:gerelateerde/>
						<ZKN:omschrijving/>
						<ZKN:code/>
						<ZKN:toelichting/>
					</ZKN:heeftAlsGemachtigde>
					<ZKN:heeftAlsInitiator StUF:entiteittype="ZAKBTRINI">
						<ZKN:gerelateerde/>
						<ZKN:omschrijving/>
						<ZKN:code/>
						<ZKN:toelichting/>
					</ZKN:heeftAlsInitiator>
					<ZKN:heeftAlsUitvoerende StUF:entiteittype="ZAKBTRUTV">
						<ZKN:gerelateerde/>
						<ZKN:omschrijving/>
						<ZKN:code/>
						<ZKN:toelichting/>
					</ZKN:heeftAlsUitvoerende>
					<ZKN:heeftAlsVerantwoordelijke StUF:entiteittype="ZAKBTRVRA">
						<ZKN:gerelateerde/>
					</ZKN:heeftAlsVerantwoordelijke>
					<ZKN:heeftAlsOverigBetrokkene StUF:entiteittype="ZAKBTROVR">
						<ZKN:gerelateerde/>
						<ZKN:omschrijving/>
						<ZKN:code/>
						<ZKN:toelichting/>
					</ZKN:heeftAlsOverigBetrokkene>
					<ZKN:heeftAlsDeelzaak StUF:entiteittype="ZAKZAKDEL">
						<ZKN:gerelateerde/>
					</ZKN:heeftAlsDeelzaak>
					<ZKN:heeftAlsHoofdzaak StUF:entiteittype="ZAKZAKHFD">
						<ZKN:gerelateerde/>
					</ZKN:heeftAlsHoofdzaak>
					<ZKN:heeftBetrekkingOpAndere StUF:entiteittype="ZAKZAKBTR">
						<ZKN:gerelateerde/>
					</ZKN:heeftBetrekkingOpAndere>
					<ZKN:heeft StUF:entiteittype="ZAKSTT">
						<ZKN:gerelateerde StUF:entiteittype="STT">
							<ZKN:code xsi:nil="true" />
							<ZKN:omschrijving xsi:nil="true" />
						</ZKN:gerelateerde>
						<ZKN:datumStatusGezet xsi:nil="true" />
						<ZKN:indicatieLaatsteStatus xsi:nil="true" />
						<ZKN:isGezetDoor StUF:entiteittype="ZAKSTTBTR">
							<ZKN:gerelateerde/>
						</ZKN:isGezetDoor>
					</ZKN:heeft>
					<ZKN:heeftRelevant StUF:entiteittype="ZAKEDC">
						<ZKN:gerelateerde StUF:entiteittype="EDC">
							<ZKN:identificatie xsi:nil="true" />
							<ZKN:creatiedatum xsi:nil="true" />
							<ZKN:ontvangstdatum xsi:nil="true" />
							<ZKN:titel xsi:nil="true" />
							<ZKN:beschrijving xsi:nil="true" />
							<ZKN:formaat xsi:nil="true" />
							<ZKN:taal xsi:nil="true" />
							<ZKN:versie xsi:nil="true" />
							<ZKN:status xsi:nil="true" />
							<ZKN:verzenddatum xsi:nil="true" />
							<ZKN:vertrouwelijkAanduiding xsi:nil="true" />
							<ZKN:inhoud xsi:nil="true" />
							<ZKN:auteur xsi:nil="true" />
							<ZKN:link xsi:nil="true" />
						</ZKN:gerelateerde>
					</ZKN:heeftRelevant>
					<ZKN:leidtTot StUF:entiteittype="ZAKBSL">
						<ZKN:gerelateerde/>
					</ZKN:leidtTot>
				</ZKN:object>
			</ZKN:scope>
		</ZKN:zakLv01>
	</soapenv:Body>
</soapenv:Envelope>
```

Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
		<SOAP-ENV:Fault>
			<faultcode xmlns:env="http://www.w3.org/2003/05/soap-envelope">env:Receiver</faultcode>
			<faultstring>java.lang.NullPointerException</faultstring>
			<detail>
				<Fo03Bericht xmlns="http://www.egem.nl/StUF/StUF0301" xmlns:ns2="http://www.egem.nl/StUF/sector/zkn/0310">
					<body>
						<code>StUF058</code>
						<plek>server</plek>
						<omschrijving>java.lang.NullPointerException</omschrijving>
						<details>java.lang.NullPointerException
							at nl.haarlem.translations.zdstozgw.converter.impl.translate.GeefZaakDetailsTranslator.execute(GeefZaakDetailsTranslator.java:38)
							at nl.haarlem.translations.zdstozgw.requesthandler.RequestHandler.execute(RequestHandler.java:82)
							at nl.haarlem.translations.zdstozgw.controller.SoapController.HandleRequest(SoapController.java:115)
							at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
							at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
							at java.base/java.lang.reflect.Method.invoke(Method.java:566)
							at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
							at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
							at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
							at org.springframework</details>
						<detailsXML>
							<todo>﻿&lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"&gt;&lt;soapenv:Header /&gt;&lt;soapenv:Body&gt;&lt;ZKN:zakLv01 xmlns:ZKN="http://www.egem.nl/StUF/sector/zkn/0310" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:BG="http://www.egem.nl/StUF/sector/bg/0310" xmlns:StUF="http://www.egem.nl/StUF/StUF0301"&gt;&lt;ZKN:stuurgegevens&gt;&lt;StUF:berichtcode&gt;Lv01&lt;/StUF:berichtcode&gt;&lt;StUF:entiteittype&gt;ZAK&lt;/StUF:entiteittype&gt;&lt;/ZKN:stuurgegevens&gt;&lt;ZKN:parameters&gt;&lt;StUF:sortering&gt;0&lt;/StUF:sortering&gt;&lt;StUF:indicatorVervolgvraag&gt;false&lt;/StUF:indicatorVervolgvraag&gt;&lt;/ZKN:parameters&gt;&lt;ZKN:gelijk StUF:entiteittype="ZAK"&gt;&lt;ZKN:heeftAlsInitiator StUF:entiteittype="ZAKBTRINI"&gt;&lt;ZKN:gerelateerde&gt;&lt;ZKN:identificatie&gt;11111111110&lt;/ZKN:identificatie&gt;&lt;/ZKN:gerelateerde&gt;&lt;/ZKN:heeftAlsInitiator&gt;&lt;/ZKN:gelijk&gt;&lt;ZKN:scope&gt;&lt;ZKN:object StUF:entiteittype="ZAK"&gt;&lt;ZKN:identificatie xsi:nil="true" /&gt;&lt;ZKN:omschrijving xsi:nil="true" /&gt;&lt;ZKN:toelichting xsi:nil="true" /&gt;&lt;ZKN:resultaat&gt;&lt;ZKN:omschrijving xsi:nil="true" /&gt;&lt;ZKN:toelichting xsi:nil="true" /&gt;&lt;/ZKN:resultaat&gt;&lt;ZKN:startdatum xsi:nil="true" /&gt;&lt;ZKN:registratiedatum xsi:nil="true" /&gt;&lt;ZKN:publicatiedatum xsi:nil="true" /&gt;&lt;ZKN:einddatumGepland xsi:nil="true" /&gt;&lt;ZKN:uiterlijkeEinddatum xsi:nil="true" /&gt;&lt;ZKN:einddatum xsi:nil="true" /&gt;&lt;ZKN:opschorting&gt;&lt;ZKN:indicatie xsi:nil="true" /&gt;&lt;ZKN:reden xsi:nil="true" /&gt;&lt;/ZKN:opschorting&gt;&lt;ZKN:verlenging&gt;&lt;ZKN:duur xsi:nil="true" /&gt;&lt;ZKN:reden xsi:nil="true" /&gt;&lt;/ZKN:verlenging&gt;&lt;ZKN:betalingsIndicatie xsi:nil="true" /&gt;&lt;ZKN:laatsteBetaaldatum xsi:nil="true" /&gt;&lt;ZKN:archiefnominatie xsi:nil="true" /&gt;&lt;ZKN:datumVernietigingDossier xsi:nil="true" /&gt;&lt;ZKN:zaakniveau xsi:nil="true" /&gt;&lt;ZKN:deelzakenIndicatie xsi:nil="true" /&gt;&lt;ZKN:isVan StUF:entiteittype="ZAKZKT"&gt;&lt;ZKN:gerelateerde StUF:entiteittype="ZKT"&gt;&lt;ZKN:omschrijving xsi:nil="true" /&gt;&lt;ZKN:code xsi:nil="true" /&gt;&lt;/ZKN:gerelateerde&gt;&lt;/ZKN:isVan&gt;&lt;ZKN:heeftBetrekkingOp StUF:entiteittype="ZAKOBJ"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;/ZKN:heeftBetrekkingOp&gt;&lt;ZKN:heeftAlsBelanghebbende StUF:entiteittype="ZAKBTRBLH"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsBelanghebbende&gt;&lt;ZKN:heeftAlsGemachtigde StUF:entiteittype="ZAKBTRGMC"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsGemachtigde&gt;&lt;ZKN:heeftAlsInitiator StUF:entiteittype="ZAKBTRINI"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsInitiator&gt;&lt;ZKN:heeftAlsUitvoerende StUF:entiteittype="ZAKBTRUTV"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsUitvoerende&gt;&lt;ZKN:heeftAlsVerantwoordelijke StUF:entiteittype="ZAKBTRVRA"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:heeftAlsVerantwoordelijke&gt;&lt;ZKN:heeftAlsOverigBetrokkene StUF:entiteittype="ZAKBTROVR"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsOverigBetrokkene&gt;&lt;ZKN:heeftAlsDeelzaak StUF:entiteittype="ZAKZAKDEL"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:heeftAlsDeelzaak&gt;&lt;ZKN:heeftAlsHoofdzaak StUF:entiteittype="ZAKZAKHFD"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:heeftAlsHoofdzaak&gt;&lt;ZKN:heeftBetrekkingOpAndere StUF:entiteittype="ZAKZAKBTR"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:heeftBetrekkingOpAndere&gt;&lt;ZKN:heeft StUF:entiteittype="ZAKSTT"&gt;&lt;ZKN:gerelateerde StUF:entiteittype="STT"&gt;&lt;ZKN:code xsi:nil="true" /&gt;&lt;ZKN:omschrijving xsi:nil="true" /&gt;&lt;/ZKN:gerelateerde&gt;&lt;ZKN:datumStatusGezet xsi:nil="true" /&gt;&lt;ZKN:indicatieLaatsteStatus xsi:nil="true" /&gt;&lt;ZKN:isGezetDoor StUF:entiteittype="ZAKSTTBTR"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:isGezetDoor&gt;&lt;/ZKN:heeft&gt;&lt;ZKN:heeftRelevant StUF:entiteittype="ZAKEDC"&gt;&lt;ZKN:gerelateerde StUF:entiteittype="EDC"&gt;&lt;ZKN:identificatie xsi:nil="true" /&gt;&lt;ZKN:creatiedatum xsi:nil="true" /&gt;&lt;ZKN:ontvangstdatum xsi:nil="true" /&gt;&lt;ZKN:titel xsi:nil="true" /&gt;&lt;ZKN:beschrijving xsi:nil="true" /&gt;&lt;ZKN:formaat xsi:nil="true" /&gt;&lt;ZKN:taal xsi:nil="true" /&gt;&lt;ZKN:versie xsi:nil="true" /&gt;&lt;ZKN:status xsi:nil="true" /&gt;&lt;ZKN:verzenddatum xsi:nil="true" /&gt;&lt;ZKN:vertrouwelijkAanduiding xsi:nil="true" /&gt;&lt;ZKN:inhoud xsi:nil="true" /&gt;&lt;ZKN:auteur xsi:nil="true" /&gt;&lt;ZKN:link xsi:nil="true" /&gt;&lt;/ZKN:gerelateerde&gt;&lt;/ZKN:heeftRelevant&gt;&lt;ZKN:leidtTot StUF:entiteittype="ZAKBSL"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:leidtTot&gt;&lt;/ZKN:object&gt;&lt;/ZKN:scope&gt;&lt;/ZKN:zakLv01&gt;&lt;/soapenv:Body&gt;&lt;/soapenv:Envelope&gt;</todo>
						</detailsXML>
					</body>
				</Fo03Bericht>
			</detail>
		</SOAP-ENV:Fault>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

```

**Comment by EduardWitteveen** [comment]
Request:

```
  <SOAP-ENV:Header/>
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <faultcode xmlns:env="http://www.w3.org/2003/05/soap-envelope">env:Receiver</faultcode>
      <faultstring>java.lang.NullPointerException</faultstring>
      <detail>
        <Fo03Bericht xmlns="http://www.egem.nl/StUF/StUF0301" xmlns:ns2="http://www.egem.nl/StUF/sector/zkn/0310">
          <body>
            <code>StUF058</code>
            <plek>server</plek>
            <omschrijving>java.lang.NullPointerException</omschrijving>
            <details>java.lang.NullPointerException
            at nl.haarlem.translations.zdstozgw.converter.impl.translate.GeefZaakDetailsTranslator.execute(GeefZaakDetailsTranslator.java:38)
            at nl.haarlem.translations.zdstozgw.requesthandler.RequestHandler.execute(RequestHandler.java:83)
            at nl.haarlem.translations.zdstozgw.controller.SoapController.HandleRequest(SoapController.java:101)
            at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
            at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
            at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
            at org.springframework</details>
            <detailsXML>
              <todo>&lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"&gt;&lt;soapenv:Header /&gt;&lt;soapenv:Body&gt;&lt;ZKN:zakLv01 xmlns:ZKN="http://www.egem.nl/StUF/sector/zkn/0310" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:BG="http://www.egem.nl/StUF/sector/bg/0310" xmlns:StUF="http://www.egem.nl/StUF/StUF0301"&gt;&lt;ZKN:stuurgegevens&gt;&lt;StUF:berichtcode&gt;Lv01&lt;/StUF:berichtcode&gt;&lt;StUF:entiteittype&gt;ZAK&lt;/StUF:entiteittype&gt;&lt;/ZKN:stuurgegevens&gt;&lt;ZKN:parameters&gt;&lt;StUF:sortering&gt;0&lt;/StUF:sortering&gt;&lt;StUF:indicatorVervolgvraag&gt;false&lt;/StUF:indicatorVervolgvraag&gt;&lt;/ZKN:parameters&gt;&lt;ZKN:gelijk StUF:entiteittype="ZAK"&gt;&lt;ZKN:heeftAlsInitiator StUF:entiteittype="ZAKBTRINI"&gt;&lt;ZKN:gerelateerde&gt;&lt;ZKN:identificatie&gt;111111110&lt;/ZKN:identificatie&gt;&lt;/ZKN:gerelateerde&gt;&lt;/ZKN:heeftAlsInitiator&gt;&lt;/ZKN:gelijk&gt;&lt;ZKN:scope&gt;&lt;ZKN:object StUF:entiteittype="ZAK"&gt;&lt;ZKN:identificatie xsi:nil="true" /&gt;&lt;ZKN:omschrijving xsi:nil="true" /&gt;&lt;ZKN:toelichting xsi:nil="true" /&gt;&lt;ZKN:resultaat&gt;&lt;ZKN:omschrijving xsi:nil="true" /&gt;&lt;ZKN:toelichting xsi:nil="true" /&gt;&lt;/ZKN:resultaat&gt;&lt;ZKN:startdatum xsi:nil="true" /&gt;&lt;ZKN:registratiedatum xsi:nil="true" /&gt;&lt;ZKN:publicatiedatum xsi:nil="true" /&gt;&lt;ZKN:einddatumGepland xsi:nil="true" /&gt;&lt;ZKN:uiterlijkeEinddatum xsi:nil="true" /&gt;&lt;ZKN:einddatum xsi:nil="true" /&gt;&lt;ZKN:opschorting&gt;&lt;ZKN:indicatie xsi:nil="true" /&gt;&lt;ZKN:reden xsi:nil="true" /&gt;&lt;/ZKN:opschorting&gt;&lt;ZKN:verlenging&gt;&lt;ZKN:duur xsi:nil="true" /&gt;&lt;ZKN:reden xsi:nil="true" /&gt;&lt;/ZKN:verlenging&gt;&lt;ZKN:betalingsIndicatie xsi:nil="true" /&gt;&lt;ZKN:laatsteBetaaldatum xsi:nil="true" /&gt;&lt;ZKN:archiefnominatie xsi:nil="true" /&gt;&lt;ZKN:datumVernietigingDossier xsi:nil="true" /&gt;&lt;ZKN:zaakniveau xsi:nil="true" /&gt;&lt;ZKN:deelzakenIndicatie xsi:nil="true" /&gt;&lt;ZKN:isVan StUF:entiteittype="ZAKZKT"&gt;&lt;ZKN:gerelateerde StUF:entiteittype="ZKT"&gt;&lt;ZKN:omschrijving xsi:nil="true" /&gt;&lt;ZKN:code xsi:nil="true" /&gt;&lt;/ZKN:gerelateerde&gt;&lt;/ZKN:isVan&gt;&lt;ZKN:heeftBetrekkingOp StUF:entiteittype="ZAKOBJ"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;/ZKN:heeftBetrekkingOp&gt;&lt;ZKN:heeftAlsBelanghebbende StUF:entiteittype="ZAKBTRBLH"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsBelanghebbende&gt;&lt;ZKN:heeftAlsGemachtigde StUF:entiteittype="ZAKBTRGMC"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsGemachtigde&gt;&lt;ZKN:heeftAlsInitiator StUF:entiteittype="ZAKBTRINI"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsInitiator&gt;&lt;ZKN:heeftAlsUitvoerende StUF:entiteittype="ZAKBTRUTV"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsUitvoerende&gt;&lt;ZKN:heeftAlsVerantwoordelijke StUF:entiteittype="ZAKBTRVRA"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:heeftAlsVerantwoordelijke&gt;&lt;ZKN:heeftAlsOverigBetrokkene StUF:entiteittype="ZAKBTROVR"&gt;&lt;ZKN:gerelateerde /&gt;&lt;ZKN:omschrijving /&gt;&lt;ZKN:code /&gt;&lt;ZKN:toelichting /&gt;&lt;/ZKN:heeftAlsOverigBetrokkene&gt;&lt;ZKN:heeftAlsDeelzaak StUF:entiteittype="ZAKZAKDEL"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:heeftAlsDeelzaak&gt;&lt;ZKN:heeftAlsHoofdzaak StUF:entiteittype="ZAKZAKHFD"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:heeftAlsHoofdzaak&gt;&lt;ZKN:heeftBetrekkingOpAndere StUF:entiteittype="ZAKZAKBTR"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:heeftBetrekkingOpAndere&gt;&lt;ZKN:heeft StUF:entiteittype="ZAKSTT"&gt;&lt;ZKN:gerelateerde StUF:entiteittype="STT"&gt;&lt;ZKN:code xsi:nil="true" /&gt;&lt;ZKN:omschrijving xsi:nil="true" /&gt;&lt;/ZKN:gerelateerde&gt;&lt;ZKN:datumStatusGezet xsi:nil="true" /&gt;&lt;ZKN:indicatieLaatsteStatus xsi:nil="true" /&gt;&lt;ZKN:isGezetDoor StUF:entiteittype="ZAKSTTBTR"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:isGezetDoor&gt;&lt;/ZKN:heeft&gt;&lt;ZKN:heeftRelevant StUF:entiteittype="ZAKEDC"&gt;&lt;ZKN:gerelateerde StUF:entiteittype="EDC"&gt;&lt;ZKN:identificatie xsi:nil="true" /&gt;&lt;ZKN:creatiedatum xsi:nil="true" /&gt;&lt;ZKN:ontvangstdatum xsi:nil="true" /&gt;&lt;ZKN:titel xsi:nil="true" /&gt;&lt;ZKN:beschrijving xsi:nil="true" /&gt;&lt;ZKN:formaat xsi:nil="true" /&gt;&lt;ZKN:taal xsi:nil="true" /&gt;&lt;ZKN:versie xsi:nil="true" /&gt;&lt;ZKN:status xsi:nil="true" /&gt;&lt;ZKN:verzenddatum xsi:nil="true" /&gt;&lt;ZKN:vertrouwelijkAanduiding xsi:nil="true" /&gt;&lt;ZKN:inhoud xsi:nil="true" /&gt;&lt;ZKN:auteur xsi:nil="true" /&gt;&lt;ZKN:link xsi:nil="true" /&gt;&lt;/ZKN:gerelateerde&gt;&lt;/ZKN:heeftRelevant&gt;&lt;ZKN:leidtTot StUF:entiteittype="ZAKBSL"&gt;&lt;ZKN:gerelateerde /&gt;&lt;/ZKN:leidtTot&gt;&lt;/ZKN:object&gt;&lt;/ZKN:scope&gt;&lt;/ZKN:zakLv01&gt;&lt;/soapenv:Body&gt;&lt;/soapenv:Envelope&gt;</todo>
            </detailsXML>
          </body>
        </Fo03Bericht>
      </detail>
    </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
