### ISSUE TITLE
Fout bij het inchecken gewijzigd document

### ISSUE THREAD

**Issue by EduardWitteveen** [Sudwest-Fryslan/OpenZaakBrug#231]
**Uitchecken**
SoapAction: http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdocumentbewerken_Di02
Request: 
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Body>
		<ZKN:geefZaakdocumentbewerken_Di02 xmlns:ZKN="http://www.egem.nl/StUF/sector/zkn/0310"
                                 			xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
                                 			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ZKN:stuurgegevens>
				<StUF:berichtcode>Di02</StUF:berichtcode>
				<StUF:zender>
					<StUF:organisatie>1900</StUF:organisatie>
					<StUF:applicatie>GISVG</StUF:applicatie>
				</StUF:zender>
				<StUF:ontvanger>
					<StUF:organisatie>1900</StUF:organisatie>
					<StUF:applicatie>ZDS</StUF:applicatie>
				</StUF:ontvanger>
				<StUF:referentienummer>ce1d37f0-96eb-49a7-a733-d247ce9080d8</StUF:referentienummer>
				<StUF:tijdstipBericht>20210805132235661</StUF:tijdstipBericht>
				<StUF:functie>geefZaakdocumentbewerken</StUF:functie>
			</ZKN:stuurgegevens>
			<ZKN:edcLv01 StUF:entiteittype="EDC"
           				StUF:functie="selectie">
				<ZKN:parameters>
					<StUF:indicatorAfnemerIndicatie>false</StUF:indicatorAfnemerIndicatie>
				</ZKN:parameters>
				<ZKN:gelijk StUF:entiteittype="EDC">
					<ZKN:identificatie>1900624733</ZKN:identificatie>
				</ZKN:gelijk>
				<ZKN:scope>
					<ZKN:object StUF:entiteittype="EDC">
						<ZKN:identificatie/>
						<ZKN:dct.omschrijving xsi:nil="true"/>
						<ZKN:dct.omschrijvingGeneriek xsi:nil="true"/>
						<ZKN:dct.categorie xsi:nil="true"/>
						<ZKN:creatiedatum>12345678</ZKN:creatiedatum>
						<ZKN:ontvangstdatum xsi:nil="true"/>
						<ZKN:titel/>
						<ZKN:beschrijving xsi:nil="true"/>
						<ZKN:formaat/>
						<ZKN:taal/>
						<ZKN:versie xsi:nil="true"/>
						<ZKN:status xsi:nil="true"/>
						<ZKN:verzenddatum xsi:nil="true"/>
						<ZKN:vertrouwelijkAanduiding>GEHEIM</ZKN:vertrouwelijkAanduiding>
						<ZKN:auteur/>
						<ZKN:link xsi:nil="true"/>
						<ZKN:inhoud/>
						<StUF:extraElementen>
							<StUF:extraElement naam=""
                 								xsi:nil="true"
                 								StUF:noValue="geenWaarde"/>
						</StUF:extraElementen>
						<ZKN:isRelevantVoor StUF:entiteittype="EDCZAK">
							<ZKN:gerelateerde StUF:entiteittype="ZAK">
								<ZKN:identificatie xsi:nil="true"
                 									StUF:noValue="geenWaarde"/>
							</ZKN:gerelateerde>
							<ZKN:titel xsi:nil="true"/>
							<ZKN:beschrijving xsi:nil="true"/>
							<ZKN:registratiedatum xsi:nil="true"/>
						</ZKN:isRelevantVoor>
					</ZKN:object>
				</ZKN:scope>
			</ZKN:edcLv01>
		</ZKN:geefZaakdocumentbewerken_Di02>
	</s:Body>
</s:Envelope>
```
Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
		<ns2:geefZaakdocumentbewerken_Du02 xmlns:ns1="http://www.egem.nl/StUF/StUF0301"
                                 			xmlns:ns2="http://www.egem.nl/StUF/sector/zkn/0310"
                                 			xmlns:ns4="http://www.egem.nl/StUF/sector/bg/0310"
                                 			xmlns:xmime="http://www.w3.org/2005/05/xmlmime">
			<ns2:stuurgegevens>
				<ns1:berichtcode>Du02</ns1:berichtcode>
				<ns1:zender>
					<ns1:organisatie>1900</ns1:organisatie>
					<ns1:applicatie>ZDS</ns1:applicatie>
				</ns1:zender>
				<ns1:ontvanger>
					<ns1:organisatie>1900</ns1:organisatie>
					<ns1:applicatie>GISVG</ns1:applicatie>
				</ns1:ontvanger>
				<ns1:referentienummer>ozb-665b8535-d7f4-4176-829e-79fa20b65c68</ns1:referentienummer>
				<ns1:tijdstipBericht>20210805132245</ns1:tijdstipBericht>
				<ns1:crossRefnummer>ce1d37f0-96eb-49a7-a733-d247ce9080d8</ns1:crossRefnummer>
				<ns1:functie>geefZaakdocumentbewerken</ns1:functie>
			</ns2:stuurgegevens>
			<ns2:parameters>
				<ns2:checkedOutId>9668fff19cdf4a9599fc59737f0ee262</ns2:checkedOutId>
			</ns2:parameters>
			<ns2:edcLa01 ns1:entiteittype="EDC"
           				ns1:functie="antwoord">
				<ns2:parameters/>
				<ns2:antwoord>
					<ns2:object ns1:entiteittype="EDC">
						<ns2:identificatie>1900624733</ns2:identificatie>
						<ns2:dct.omschrijving>Aanvraag</ns2:dct.omschrijving>
						<ns2:creatiedatum>20210805</ns2:creatiedatum>
						<ns2:ontvangstdatum>00010101</ns2:ontvangstdatum>
						<ns2:titel>test.txt</ns2:titel>
						<ns2:beschrijving>test 1</ns2:beschrijving>
						<ns2:formaat>txt</ns2:formaat>
						<ns2:taal>nld</ns2:taal>
						<ns2:versie>1</ns2:versie>
						<ns2:vertrouwelijkAanduiding>INTERN</ns2:vertrouwelijkAanduiding>
						<ns2:auteur>s.ykema</ns2:auteur>
						<ns2:link/>
						<ns2:inhoud ns1:bestandsnaam="test.txt"
          							xmime:contentType="text/plain">ZGl0IGlzIGVlbiB0ZXN0IDE=</ns2:inhoud>
						<ns2:isRelevantVoor ns1:entiteittype="EDCZAK">
							<ns2:gerelateerde ns1:entiteittype="ZAK">
								<ns2:identificatie>1900225923</ns2:identificatie>
								<ns2:omschrijving>Dossiernummer GISVG OV20200050</ns2:omschrijving>
							</ns2:gerelateerde>
						</ns2:isRelevantVoor>
					</ns2:object>
				</ns2:antwoord>
			</ns2:edcLa01>
		</ns2:geefZaakdocumentbewerken_Du02>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
SoapAction: http://www.egem.nl/StUF/sector/zkn/0310/updateZaakdocument_Di02
Request:
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Body>
		<updateZaakdocument_Di02 xmlns="http://www.egem.nl/StUF/sector/zkn/0310"
                       			xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
                       			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<stuurgegevens>
				<StUF:berichtcode>Di02</StUF:berichtcode>
				<StUF:zender>
					<StUF:organisatie>1900</StUF:organisatie>
					<StUF:applicatie>GISVG</StUF:applicatie>
				</StUF:zender>
				<StUF:ontvanger>
					<StUF:organisatie>1900</StUF:organisatie>
					<StUF:applicatie>ZDS</StUF:applicatie>
				</StUF:ontvanger>
				<StUF:referentienummer>cb976021-92fc-45bd-9ea8-cdd4ffa640f0</StUF:referentienummer>
				<StUF:tijdstipBericht>20210805132347264</StUF:tijdstipBericht>
				<StUF:functie>updateZaakdocument</StUF:functie>
			</stuurgegevens>
			<parameters>
				<checkedOutId>9668fff19cdf4a9599fc59737f0ee262</checkedOutId>
			</parameters>
			<edcLk02 StUF:entiteittype="EDC"
       				StUF:functie="update">
				<parameters>
					<StUF:mutatiesoort>W</StUF:mutatiesoort>
				</parameters>
				<object StUF:entiteittype="EDC"
      					StUF:verwerkingssoort="W">
					<identificatie>1900624733</identificatie>
					<titel>test.txt</titel>
					<beschrijving>test 1</beschrijving>
					<taal>nld</taal>
					<vertrouwelijkAanduiding>INTERN</vertrouwelijkAanduiding>
					<auteur>s.ykema</auteur>
					<inhoud a:contentType="text/plain"
      						StUF:bestandsnaam="test.txt"
      						xmlns:a="http://www.w3.org/2005/05/xmlmime">ZGl0IGlzIGVlbiB0ZXN0IDE=</inhoud>
				</object>
				<object StUF:entiteittype="EDC"
      					StUF:verwerkingssoort="W">
					<identificatie>1900624733</identificatie>
					<titel>test.txt</titel>
					<beschrijving/>
					<taal>NL</taal>
					<vertrouwelijkAanduiding>INTERN</vertrouwelijkAanduiding>
					<auteur>s.ykema</auteur>
					<inhoud a:contentType="text/plain"
      						StUF:bestandsnaam="test.txt"
      						xmlns:a="http://www.w3.org/2005/05/xmlmime">ZGl0IGlzIGVlbiB0ZXN0IDENCg0Kd2lqemlnZW4=</inhoud>
				</object>
			</edcLk02>
		</updateZaakdocument_Di02>
	</s:Body>
</s:Envelope>

```

Response:
```

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
		<SOAP-ENV:Fault>
			<faultcode xmlns:env="http://www.w3.org/2003/05/soap-envelope">env:Receiver</faultcode>
			<faultstring>java.lang.NullPointerException</faultstring>
			<detail>
				<Fo03Bericht xmlns="http://www.egem.nl/StUF/StUF0301"
           					xmlns:ns2="http://www.egem.nl/StUF/sector/zkn/0310">
					<stuurgegevens>
						<berichtcode>Fo03</berichtcode>
						<zender>
							<organisatie>1900</organisatie>
							<applicatie>ZDS</applicatie>
						</zender>
						<ontvanger>
							<organisatie>1900</organisatie>
							<applicatie>GISVG</applicatie>
						</ontvanger>
						<referentienummer>ozb-6c8c7d83-fb86-4469-9abe-69dc0bbbf100</referentienummer>
						<tijdstipBericht>20210805132348</tijdstipBericht>
						<crossRefnummer>cb976021-92fc-45bd-9ea8-cdd4ffa640f0</crossRefnummer>
					</stuurgegevens>
					<body>
						<code>StUF058</code>
						<plek>server</plek>
						<omschrijving>java.lang.NullPointerException</omschrijving>
						<details>java.lang.NullPointerException
							at nl.haarlem.translations.zdstozgw.translation.zds.services.ZaakService.updateZaakDocument(ZaakService.java:906)
							at nl.haarlem.translations.zdstozgw.converter.impl.translate.UpdateZaakdocumentTranslator.execute(UpdateZaakdocumentTranslator.java:41)
							at nl.haarlem.translations.zdstozgw.requesthandler.RequestHandler.execute(RequestHandler.java:83)
							at nl.haarlem.translations.zdstozgw.controller.SoapController.HandleRequest(SoapController.java:101)
							at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
							at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
							at java.base/java.lang.reflect.Method.invoke(Method.java:566)
							at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
							at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
							at org.springframework.web.servlet.mvc.method</details>
						<detailsXML>
							<todo>&lt;s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"&gt;&lt;s:Body&gt;&lt;updateZaakdocument_Di02 xmlns="http://www.egem.nl/StUF/sector/zkn/0310" xmlns:StUF="http://www.egem.nl/StUF/StUF0301" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;&lt;stuurgegevens&gt;&lt;StUF:berichtcode&gt;Di02&lt;/StUF:berichtcode&gt;&lt;StUF:zender&gt;&lt;StUF:organisatie&gt;1900&lt;/StUF:organisatie&gt;&lt;StUF:applicatie&gt;GISVG&lt;/StUF:applicatie&gt;&lt;/StUF:zender&gt;&lt;StUF:ontvanger&gt;&lt;StUF:organisatie&gt;1900&lt;/StUF:organisatie&gt;&lt;StUF:applicatie&gt;ZDS&lt;/StUF:applicatie&gt;&lt;/StUF:ontvanger&gt;&lt;StUF:referentienummer&gt;cb976021-92fc-45bd-9ea8-cdd4ffa640f0&lt;/StUF:referentienummer&gt;&lt;StUF:tijdstipBericht&gt;20210805132347264&lt;/StUF:tijdstipBericht&gt;&lt;StUF:functie&gt;updateZaakdocument&lt;/StUF:functie&gt;&lt;/stuurgegevens&gt;&lt;parameters&gt;&lt;checkedOutId&gt;9668fff19cdf4a9599fc59737f0ee262&lt;/checkedOutId&gt;&lt;/parameters&gt;&lt;edcLk02 StUF:entiteittype="EDC" StUF:functie="update"&gt;&lt;parameters&gt;&lt;StUF:mutatiesoort&gt;W&lt;/StUF:mutatiesoort&gt;&lt;/parameters&gt;&lt;object StUF:entiteittype="EDC" StUF:verwerkingssoort="W"&gt;&lt;identificatie&gt;1900624733&lt;/identificatie&gt;&lt;titel&gt;test.txt&lt;/titel&gt;&lt;beschrijving&gt;test 1&lt;/beschrijving&gt;&lt;taal&gt;nld&lt;/taal&gt;&lt;vertrouwelijkAanduiding&gt;INTERN&lt;/vertrouwelijkAanduiding&gt;&lt;auteur&gt;s.ykema&lt;/auteur&gt;&lt;inhoud a:contentType="text/plain" StUF:bestandsnaam="test.txt" xmlns:a="http://www.w3.org/2005/05/xmlmime"&gt;ZGl0IGlzIGVlbiB0ZXN0IDE=&lt;/inhoud&gt;&lt;/object&gt;&lt;object StUF:entiteittype="EDC" StUF:verwerkingssoort="W"&gt;&lt;identificatie&gt;1900624733&lt;/identificatie&gt;&lt;titel&gt;test.txt&lt;/titel&gt;&lt;beschrijving&gt;&lt;/beschrijving&gt;&lt;taal&gt;NL&lt;/taal&gt;&lt;vertrouwelijkAanduiding&gt;INTERN&lt;/vertrouwelijkAanduiding&gt;&lt;auteur&gt;s.ykema&lt;/auteur&gt;&lt;inhoud a:contentType="text/plain" StUF:bestandsnaam="test.txt" xmlns:a="http://www.w3.org/2005/05/xmlmime"&gt;ZGl0IGlzIGVlbiB0ZXN0IDENCg0Kd2lqemlnZW4=&lt;/inhoud&gt;&lt;/object&gt;&lt;/edcLk02&gt;&lt;/updateZaakdocument_Di02&gt;&lt;/s:Body&gt;&lt;/s:Envelope&gt;</todo>
						</detailsXML>
					</body>
				</Fo03Bericht>
			</detail>
		</SOAP-ENV:Fault>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

```

**Comment by EduardWitteveen** [comment]
Seems to work
