### ISSUE TITLE
Nullpointer exception in voegZaakDocumentToe

### ISSUE THREAD

**Issue by EduardWitteveen** [Sudwest-Fryslan/OpenZaakBrug#261]
<faultstring>java.lang.NullPointerException</faultstring>
	<details>java.lang.NullPointerException
	at nl.haarlem.translations.zdstozgw.translation.zds.services.ZaakService.voegZaakDocumentToe(ZaakService.java:531)
	at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.copyDocument(Replicator.java:224)
	at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.checkVoegZaakDocumentToe(Replicator.java:167)
	at nl.haarlem.translations.zdstozgw.converter.impl.replicate.Replicator.replicateZaak(Replicator.java:80)
	at nl.haarlem.translations.zdstozgw.converter.impl.replicate.GeefZaakDetailsReplicator.execute(GeefZaakDetailsReplicator.java:51)
	at nl.haarlem.translations.zdstozgw.requesthandler.RequestHandler.execute(RequestHandler.java:98)
	at nl.haarlem.translations.zdstozgw.controller.SoapController.HandleRequest(SoapController.java:116)
	at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at j</details>

**Comment by EduardWitteveen** [comment]
closed by #261
