### ISSUE TITLE
Get Centric Leefomgeving working (CLO)

### ISSUE THREAD

**Issue by EduardWitteveen** [Sudwest-Fryslan/OpenZaakBrug#328]
We are trying to get clo working by doing a lot of different actions.
The purpose of this issue is to put all the different actions together and have an high-over view

**Comment by EduardWitteveen** [comment]
Request:

```xml
<s:Envelope xmlns:s=http://schemas.xmlsoap.org/soap/envelope/><s:Header><ActivityId xmlns=http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics>7122f79c-07b5-45e7-9a00-d6fbc1a9f998</ActivityId><x-request-application xmlns=http://schemas.centric.com/2020/02/IdentityModel/Claims>198005F2F1AC7B330EC7F46DA1321178907C2983</x-request-application></s:Header><s:Body><updateZaakdocument_Di02 xmlns=http://www.egem.nl/StUF/sector/zkn/0310 xmlns:StUF=http://www.egem.nl/StUF/StUF0301 xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance>
<stuurgegevens>
<StUF:berichtcode>Di02</StUF:berichtcode>
<StUF:zender>
<StUF:organisatie>1900</StUF:organisatie>
<StUF:applicatie>CLO</StUF:applicatie>
<StUF:gebruiker>Aanmelder</StUF:gebruiker>
</StUF:zender>
<StUF:ontvanger>
<StUF:organisatie>1900</StUF:organisatie>
<StUF:applicatie>CDR</StUF:applicatie>
</StUF:ontvanger>
<StUF:referentienummer>ee49269a-806e-491c-b12c-23c2cf2efe8e</StUF:referentienummer>
<StUF:tijdstipBericht>20240318161350039</StUF:tijdstipBericht>
<StUF:functie>updateZaakdocument</StUF:functie>
</stuurgegevens>
<parameters>
<checkedOutId>78f97435556d4ac4a068fee98d662a5e</checkedOutId>
</parameters>
<edcLk02 StUF:entiteittype="EDC" StUF:functie="update">
<parameters>
<StUF:mutatiesoort>W</StUF:mutatiesoort>
</parameters>
<object StUF:entiteittype="EDC" StUF:verwerkingssoort="W">
<identificatie>19001060497</identificatie>
<dct.omschrijving>Aanvraag omgevingsvergunning</dct.omschrijving>
<creatiedatum>20240318</creatiedatum>
<titel>aanvullingen</titel>
<formaat>jpg</formaat>
<taal>nl</taal>
<versie>2</versie>
<status>In bewerking</status>
<vertrouwelijkAanduiding>VERTROUWELIJK</vertrouwelijkAanduiding>
<auteur>Aanmelder</auteur>
<inhoud a:contentType="image/jpeg" StUF:bestandsnaam="aanvullingen.jpg" xmlns:a=http://www.w3.org/2005/05/xmlmime>....</inhoud>
<isRelevantVoor StUF:entiteittype="EDCZAK" StUF:verwerkingssoort="T">
<gerelateerde StUF:entiteittype="ZAK" StUF:verwerkingssoort="T">
<identificatie>1900576688</identificatie>
<omschrijving>test 3</omschrijving>
<isVan StUF:entiteittype="ZAKZKT" StUF:verwerkingssoort="T">
<gerelateerde StUF:entiteittype="ZKT" StUF:verwerkingssoort="T">
<omschrijving>Omgevingsvergunning regulier</omschrijving>
<code>B1210</code>
<ingangsdatumObject xsi:nil="true" StUF:noValue="waardeOnbekend"></ingangsdatumObject>
</gerelateerde>
</isVan>
</gerelateerde>
</isRelevantVoor>
</object>
</edcLk02>
</updateZaakdocument_Di02></s:Body></s:Envelope>
```

Response:
```xml
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV=http://schemas.xmlsoap.org/soap/envelope/>

	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
	<SOAP-ENV:Fault>
	<faultcode xmlns:env=http://www.w3.org/2003/05/soap-envelope>env:Receiver</faultcode>

	<faultstring>java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1</faultstring>
	<detail>
	<Fo03Bericht xmlns=http://www.egem.nl/StUF/StUF0301 xmlns:ns2=http://www.egem.nl/StUF/sector/zkn/0310>

	<stuurgegevens>
	<berichtcode>Fo03</berichtcode>
	<zender>
	<organisatie>1900</organisatie>
	<applicatie>CDR</applicatie>
	</zender>
	<ontvanger>
	<organisatie>1900</organisatie>
	<applicatie>CLO</applicatie>
	<gebruiker>sykema</gebruiker>
	</ontvanger>
	<referentienummer>ozb-9a98e617-1060-4a38-9fb8-59c43760ccf5</referentienummer>
	<tijdstipBericht>20240318161351</tijdstipBericht>
	<crossRefnummer>ee49269a-806e-491c-b12c-23c2cf2efe8e</crossRefnummer>
	</stuurgegevens>
	<body>
	<code>StUF058</code>
	<plek>server</plek>
	<omschrijving>java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1</omschrijving>
	<details>java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at nl.haarlem.translations.zdstozgw.converter.impl.translate.UpdateZaakdocumentTranslator.execute(UpdateZaakdocumentTranslator.java:46)
	at nl.haarlem.translations.zdstozgw.requesthandler.RequestHandler.execute(RequestHandler.java:98)
	at nl.haarlem.translations.zdstozgw.controller.SoapController.HandleRequest(SoapController.java:131)
	at jdk.internal.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Met</details>
	<detailsXML>
	<todo>&lt;s:Envelope xmlns:s=http://schemas.xmlsoap.org/soap/envelope/&gt;&lt;s:Header&gt;&lt;ActivityId xmlns=http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics&gt;7122f79c-07b5-45e7-9a00-d6fbc1a9f998&lt;/ActivityId&gt;&lt;x-request-application xmlns=http://schemas.centric.com/2020/02/IdentityModel/Claims&gt;198005F2F1AC7B330EC7F46DA1321178907C2983&lt;/x-request-application&gt;&lt;/s:Header&gt;&lt;s:Body&gt;&lt;updateZaakdocument_Di02 xmlns=http://www.egem.nl/StUF/sector/zkn/0310 xmlns:StUF=http://www.egem.nl/StUF/StUF0301 xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance&gt;

	&lt;stuurgegevens&gt;
	&lt;StUF:berichtcode&gt;Di02&lt;/StUF:berichtcode&gt;
	&lt;StUF:zender&gt;
	&lt;StUF:organisatie&gt;1900&lt;/StUF:organisatie&gt;
	&lt;StUF:applicatie&gt;CLO&lt;/StUF:applicatie&gt;
	&lt;StUF:gebruiker&gt;Aanmelder&lt;/StUF:gebruiker&gt;
	&lt;/StUF:zender&gt;
	&lt;StUF:ontvanger&gt;
	&lt;StUF:organisatie&gt;1900&lt;/StUF:organisatie&gt;
	&lt;StUF:applicatie&gt;CDR&lt;/StUF:applicatie&gt;
	&lt;/StUF:ontvanger&gt;
	&lt;StUF:referentienummer&gt;ee49269a-806e-491c-b12c-23c2cf2efe8e&lt;/StUF:referentienummer&gt;
	&lt;StUF:tijdstipBericht&gt;20240318161350039&lt;/StUF:tijdstipBericht&gt;
	&lt;StUF:functie&gt;updateZaakdocument&lt;/StUF:functie&gt;
	&lt;/stuurgegevens&gt;
	&lt;parameters&gt;
	&lt;checkedOutId&gt;78f97435556d4ac4a068fee98d662a5e&lt;/checkedOutId&gt;
	&lt;/parameters&gt;
	&lt;edcLk02 StUF:entiteittype="EDC" StUF:functie="update"&gt;
	&lt;parameters&gt;
	&lt;StUF:mutatiesoort&gt;W&lt;/StUF:mutatiesoort&gt;
	&lt;/parameters&gt;
	&lt;object StUF:entiteittype="EDC" StUF:verwerkingssoort="W"&gt;
	&lt;identificatie&gt;19001060497&lt;/identificatie&gt;
	&lt;dct.omschrijving&gt;Aanvraag omgevingsvergunning&lt;/dct.omschrijving&gt;
	&lt;creatiedatum&gt;20240318&lt;/creatiedatum&gt;
	&lt;titel&gt;aanvullingen&lt;/titel&gt;
	&lt;formaat&gt;jpg&lt;/formaat&gt;
	&lt;taal&gt;nl&lt;/taal&gt;
	&lt;versie&gt;2&lt;/versie&gt;
	&lt;status&gt;In bewerking&lt;/status&gt;
	&lt;vertrouwelijkAanduiding&gt;VERTROUWELIJK&lt;/vertrouwelijkAanduiding&gt;
	&lt;auteur&gt;Aanmelder&lt;/auteur&gt;
	&lt;inhoud a:contentType="image/jpeg" StUF:bestandsnaam="aanvullingen.jpg" ....... &lt;/inhoud&gt;
	&lt;isRelevantVoor StUF:entiteittype="EDCZAK" StUF:verwerkingssoort="T"&gt;
	&lt;gerelateerde StUF:entiteittype="ZAK" StUF:verwerkingssoort="T"&gt;
	&lt;identificatie&gt;1900576688&lt;/identificatie&gt;
	&lt;omschrijving&gt;test 3&lt;/omschrijving&gt;
	&lt;isVan StUF:entiteittype="ZAKZKT" StUF:verwerkingssoort="T"&gt;
	&lt;gerelateerde StUF:entiteittype="ZKT" StUF:verwerkingssoort="T"&gt;
	&lt;omschrijving&gt;Omgevingsvergunning regulier&lt;/omschrijving&gt;
	&lt;code&gt;B1210&lt;/code&gt;
	&lt;ingangsdatumObject xsi:nil="true" StUF:noValue="waardeOnbekend"&gt;&lt;/ingangsdatumObject&gt;
	&lt;/gerelateerde&gt;
	&lt;/isVan&gt;
	&lt;/gerelateerde&gt;
	&lt;/isRelevantVoor&gt;
	&lt;/object&gt;
	&lt;/edcLk02&gt;
	&lt;/updateZaakdocument_Di02&gt;&lt;/s:Body&gt;&lt;/s:Envelope&gt;</todo>
	</detailsXML>
	</body>
	</Fo03Bericht>
	</detail>
	</SOAP-ENV:Fault>
	</SOAP-ENV:Body>
	</SOAP-ENV:Envelope>
```
